### ISSUE TITLE
[1.12.2] Random crash when breaking blocks

### ISSUE THREAD

**Issue by ghost** [Funwayguy/RealisticItemDrops#10]
I was just breaking some dirt with an excavator from tinkers constructor all fine then it crashed
Crash report: https://pastebin.com/hay9THvW
Version: RealisticItemDrops-1.2.11

**Comment by ghost** [comment]
Oops I think I just derped now that I read the report it seems it's on swing through grass mod not this one, sorry!

**Comment by Funwayguy** [comment]
That's an interesting oversight. I wonder what the code is doing to consider everything an EntityLivingBase type. I wonder if other entities like minecarts would do this
