### ISSUE TITLE
[1.12.2] "EntityItem to world with a invalid item" console spam

### ISSUE THREAD

**Issue by Rsslone** [Funwayguy/RealisticItemDrops#13]
[Server thread/WARN] [FML]: Attempted to add a EntityItem to the world with a invalid item at (19.63,  22.42, -832.54), this is most likely a config issue between you and the server. Please double check your configs

forge-1.12.2-14.23.4.2705-universal
spongeforge-1.12.2-2705-7.1.0-BETA-3136
RealisticItemDrops-1.2.12

**Comment by Funwayguy** [comment]
There's an experimental dupe patch option in the config. Try disabling that if it's on.

**Comment by Rsslone** [comment]
Can confirm this fixes the issue. For anyone having the same problem set:

    # A workaround for machines that check their drops before subtracting items. Disable if there are noticable side effects [default: true]
    B:"Dupe Workaround"=false
