### ISSUE TITLE
Ticking entity

### ISSUE THREAD

**Issue by nlxdodge** [Funwayguy/RealisticItemDrops#2]
`---- Minecraft Crash Report ----

WARNING: coremods are present:
  ProgressionTransformer (Progression-1.9.4-0.5.2.jar)
  Reborn Core ASM (RebornCore-1.9.4-2.5.1.35-universal.jar)
Contact their authors BEFORE contacting forge

// You should try our sister game, Minceraft!

Time: 7-6-16 9:48
Description: Ticking entity

java.lang.NoSuchMethodError: net.minecraft.entity.item.EntityItem.func_174872_o()I
	at realdrops.entities.EntityItemLoot.func_70071_h_(EntityItemLoot.java:48)
	at net.minecraft.world.World.func_72866_a(World.java:1951)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:837)
	at net.minecraft.world.World.func_72870_g(World.java:1920)
	at net.minecraft.world.World.func_72939_s(World.java:1743)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:618)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:707)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:385)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:611)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:469)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at realdrops.entities.EntityItemLoot.func_70071_h_(EntityItemLoot.java:48)
	at net.minecraft.world.World.func_72866_a(World.java:1951)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:837)
	at net.minecraft.world.World.func_72870_g(World.java:1920)

-- Entity being ticked --
Details:
	Entity Type: realdrops.item_loot (realdrops.entities.EntityItemLoot)
	Entity ID: 112
	Entity Name: item.tile.doublePlant.rose
	Entity's Exact location: 157,10, 70,00, 95,45
	Entity's Block location: World: (157,70,95), Chunk: (at 13,4,15 in 9,5; contains blocks 144,0,80 to 159,255,95), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Entity's Momentum: -0,00, -0,00, -0,00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1743)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:618)

-- Affected level --
Details:
	Level name: world
	All players: 0 total; []
	Chunk stats: ServerChunkCache: 625 Drop: 0
	Level seed: 8812674154627713038
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (200,64,248), Chunk: (at 8,4,8 in 12,15; contains blocks 192,0,240 to 207,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 34249 game time, 34249 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 117968 (now: false), thunder time: 67534 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:707)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:385)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:611)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:469)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.9.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_72, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 196709864 bytes (187 MB) / 555745280 bytes (530 MB) up to 954728448 bytes (910 MB)
	JVM Flags: 2 total; -Xms128M -Xmx1024M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.28 Powered by Forge 12.17.0.1954 40 mods loaded, 40 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.9.4-12.17.0.1954-universal.jar) 
	UCHIJAAAA	Forge{12.17.0.1954} [Minecraft Forge] (forge-1.9.4-12.17.0.1954-universal.jar) 
	UCHIJAAAA	BiomesOPlenty{4.1.0.2025} [Biomes O' Plenty] (BiomesOPlenty-1.9.4-4.1.0.2025-universal.jar) 
	UCHIJAAAA	BloodMagic{1.9.4-2.0.1-42} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.9.4-2.0.1-42.jar) 
	UCHIJAAAA	bookshelf{1.2.2.254} [Bookshelf] (Bookshelf-1.9.4-1.2.2.254.jar) 
	UCHIJAAAA	Chameleon{1.9-2.1.4} [Chameleon] (Chameleon-1.9-2.1.4.jar) 
	UCHIJAAAA	chiselsandbits{10.4} [Chisels & Bits] (chiselsandbits-10.4.jar) 
	UCHIJAAAA	cyclopscore{0.6.3} [Cyclops Core] (CyclopsCore-1.9.4-0.6.3.jar) 
	UCHIJAAAA	DarkUtils{1.1.0.39} [Dark Utilities] (DarkUtilities-1.9.4-1.1.0.40.jar) 
	UCHIJAAAA	ElecCore{1.5.292} [ElecCore] (ElecCore-1.9.4-1.5.292.jar) 
	UCHIJAAAA	deepresonance{1.1.4beta32} [DeepResonance] (deepresonance-1.9.4-1.1.4beta32.jar) 
	UCHIJAAAA	EnderZoo{1.9.4-1.2.2.40} [Ender Zoo] (EnderZoo-1.9.4-1.2.2.40.jar) 
	UCHIJAAAA	evilcraft{0.10.2} [EvilCraft] (EvilCraft-1.9.4-0.10.2.jar) 
	UCHIJAAAA	FFS{1.9.4-1.6.0-b19} [Fancy Fluid Storage] (Fancy Fluid Storage-1.9.4-1.6.0-b19.jar) 
	UCHIJAAAA	FastLeaveDecay{1.1} [Fast Leave Decay] (FastLeaveDecay-MC1.9.4-1.2.1.jar) 
	UCHIJAAAA	Flamingo{1.8.8-1.4} [Pink Flamingo] (Flamingo-1.9.4-1.8.jar) 
	UCHIJAAAA	grapplemod{1.9.4-v7} [Grappling hook mod] (grapplemod-1.9.4-v7.jar) 
	UCHIJAAAA	gravestone{1.3.0} [Gravestone] (Gravestone Mod 1.3.0.jar) 
	UCHIJAAAA	integrateddynamics{0.3.10} [Integrated Dynamics] (IntegratedDynamics-1.9.4-0.3.10.jar) 
	UCHIJAAAA	IronChest{6.0.141.782} [Iron Chest] (ironchest-1.9.4-6.0.141.782.jar) 
	UCHIJAAAA	lightningcraft{2.3.3} [LightningCraft] (lightningcraft-2.3.3-[1.9.4].jar) 
	UCHIJAAAA	mantle{1.9.4-0.10.1.jenkins142} [Mantle] (Mantle-1.9.4-0.10.1.jenkins142.jar) 
	UCHIJAAAA	testdummy{1.10} [MmmMmmMmmMmm] (MmmMmmMmmMmm-1.11.jar) 
	UCHIJAAAA	Morphtool{GRADLE:VERSION-GRADLE:BUILD} [Morph-o-Tool] (Morph-o-Tool-1.0-2.jar) 
	UCHIJAAAA	netherportalfix{1.0} [Nether Portal Fix] (netherportalfix-mc1.9.4-4.0.1.jar) 
	UCHIJAAAA	progression{0.5.2} [Progression] (Progression-1.9.4-0.5.2.jar) 
	UCHIJAAAA	progressiveautomation{1.6.46} [Progressive Automation] (ProgressiveAutomation-1.9.4-1.6.46.jar) 
	UCHIJAAAA	quantumflux{2.0.7} [QuantumFlux] (quantumflux-1.9.4-2.0.7.jar) 
	UCHIJAAAA	Quark{beta-21} [Quark] (Quark-beta-21.jar) 
	UCHIJAAAA	realdrops{1.0.2} [Realistic Item Drops] (RealisticItemDrops-1.0.2.jar) 
	UCHIJAAAA	reborncore{2.5.1.35} [RebornCore] (RebornCore-1.9.4-2.5.1.35-universal.jar) 
	UCHIJAAAA	reborncore-mcmultipart{2.5.1.35} [reborncore-MCMultiPart] (RebornCore-1.9.4-2.5.1.35-universal.jar) 
	UCHIJAAAA	refinedstorage{0.7.8} [Refined Storage] (refinedstorage-0.7.8.jar) 
	UCHIJAAAA	rftools{4.51} [RFTools] (rftools-1.9.4-4.51.jar) 
	UCHIJAAAA	soulshardstow{1.9.4-2.4.0-28} [Soul Shards - The Old Ways] (SoulShards-TOW-1.9.4-2.4.0-28.jar) 
	UCHIJAAAA	StorageDrawers{1.9-3.1.7} [Storage Drawers] (StorageDrawers-1.9-3.1.7.jar) 
	UCHIJAAAA	structuredcrafting{0.1.5} [Structured Crafting] (StructuredCrafting-1.9.4-0.1.5.jar) 
	UCHIJAAAA	techreborn{1.3.1.100} [TechReborn] (TechReborn-1.9.4-1.3.1.100-universal.jar) 
	UCHIJAAAA	tis3d{0.9.0.5} [TIS-3D] (TIS-3D-MC1.9.4-0.9.0.5.jar) 
	Loaded coremods (and transformers): 
ProgressionTransformer (Progression-1.9.4-0.5.2.jar)
  joshie.progression.asm.ProgressionTransformer
Reborn Core ASM (RebornCore-1.9.4-2.5.1.35-universal.jar)
  reborncore.asm.RebornClassTransformer
	Profiler Position: N/A (disabled)
	Player Count: 0 / 20; []
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)`

I have no idea what this it. Just posting the logs.
The mod list can also be read above.

Is this mod not supposed to be on the server side?
Because I did read so somewhere.

**Comment by Funwayguy** [comment]
Care to provide a description of what you were doing at the time of the crash?

**Comment by nlxdodge** [comment]
Well the server was just starting nothing more.

But I see that you already found the cause. Good to know :+1:
